### ISSUE TITLE
Other text inputs losing focus when workbook is rendered.

### ISSUE THREAD

**Issue by sandilya28** [ruilisi/fortune-sheet#212] opened 2023-01-25 18:21 UTC
**Describe the bug**
I'm rendering a WorkBook as an output of a cell. 

```
              <Box
                style={{
                  display: "flex",
                  width: "100%",
                  height: "300px",
                }}
              >
                <Workbook
                  showToolbar={false}
                  showSheetTabs={false}
                  data={[
                    {
                      name: "Sheet1",
                      celldata: newCellData,
                    },
                  ]}
                />
              </Box>
```

When I'm typing text in any other text field in the page, the formula bar is taking the focus. As shown below,

![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/6747531/214211969-32f9a249-cc8c-434a-a4c7-39796e755dc3.gif)

Is there any way, we can avoid the formula bar from taking the focus.

**Comment by shuanhukexuejia** [comment] 2023-01-29 02:10
I don't see the cursor in fxInput, Its content is synchronized with the content of the inputbox. Did this cause any problem?

**Comment by sandilya28** [comment] 2023-01-29 03:19
Yes, the cursor isn't visible in the fxInput. But, when I'm trying to type in input across the page, it's losing focus.

**Comment by shuanhukexuejia** [comment] 2023-01-30 02:20
I didn't replicate the problem in the demo, can you show how to replicate the problem or can you provide a minimal reproducible demo?

**Comment by sandilya28** [comment] 2023-01-30 09:57
1. Go to the following [link](https://app-frontend-dsrpzqctwa-el.a.run.app/)
2. Add a SQL cell from the menu
3. Paste the following code in the cell, `select * from duckdb_functions()` and click on the play icon
4. The output renders in a Workbook.
5. Try editing the code by putting the cursor on the input text area.

**Comment by shuanhukexuejia** [comment] 2023-01-30 12:16
What is the event when clicking the input text area, i saw the activeElement is the cellInput.
<img width="472" alt="image" src="https://user-images.githubusercontent.com/84694078/215474267-5c6dce36-8a77-440a-8df4-640c9e293199.png">

**Comment by sandilya28** [comment] 2023-01-30 13:59
We are using monaco-editor as the input cell, 

    editorRef.current!!.onDidFocusEditorWidget(handleOnFocusEditorWidget);
    editorRef.current!!.onDidBlurEditorWidget(handleOnBlurEditorWidget);

we have two onDidFocus and onDidBlur event handlers, 

```
  const handleOnFocusEditorWidget = () => {
    containerRef!!.current!!.style.boxShadow =
      "rgb(54, 92, 163) 0px 0px 0px 1px, rgba(72, 113, 194, 0.1) 0px 0px 0px 3px, rgba(11, 14, 22, 0.05) 0px 8px 16px 0px, rgba(11, 14, 22, 0.1) 0px 1px 4px 0px";
    setFocus(true);
  };

  const handleOnBlurEditorWidget = () => {
    containerRef!!.current!!.style.boxShadow =
      "rgb(11 14 22 / 8%) 0px 0px 2px, rgb(11 14 22 / 5%) 0px 0px 0px 1px, rgb(11 14 22 / 3%) 0px 2px 4px";
    setFocus(false);
  };
```

**Comment by shuanhukexuejia** [comment] 2023-01-30 17:03
You can try 0.13.1-beta.2 to see if the problem is solved

**Comment by shuanhukexuejia** [comment] 2023-02-03 07:59
#230 This fix will be included in next release.

**Closed** 2023-02-06 09:52 UTC
